behaviors:
  ACA:
    trainer_type: sac
    hyperparameters:
      batch_size: 32
      buffer_size: 100000
      buffer_init_steps: 2500
      learning_rate_schedule: constant
      init_entcoef: 0.2
      tau: 0.007
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 999999999999999999
    time_horizon: 64
    summary_freq: 1000
    threaded: true
engine_settings:
  time_scale: 10
